services:
  - type: web
    name: Hunting-Exoplanets
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

